import forecastJson from './qualification-forecast.json'
import { getTournaments } from '@/services/api'
import type { ForecastCategory, ForecastEntry, PlayerForecast } from './qualification-odds'

// Generated by scripts/update_forecast.py; the deploy workflow rejects a stale file.
// Import only from server components so the full file isn't shipped to the browser.
interface ForecastFile {
  season: number
  after: { id: string; name: string }
  sims: number
  remaining: Array<{ id: string; name: string; start_date: string }>
  tournaments: Record<string, number>
  categories: Record<ForecastCategory, { cutoff: Array<number | null>; players: Record<string, ForecastEntry> }>
}

const forecast = forecastJson as unknown as ForecastFile

// Results edited outside the release workflow (e.g. the production admin page) reach the API
// without a new forecast, so only show odds while the API's tournaments match the ones modelled.
async function matchesPublishedResults(season: number): Promise<boolean> {
  try {
    const tournaments = await getTournaments({ season })
    const modelled = Object.keys(forecast.tournaments)
    return tournaments.length === modelled.length &&
      tournaments.every(t => forecast.tournaments[t.id] === t.results)
  } catch {
    return false
  }
}

export async function getPlayerForecast(
  fideId: string | null | undefined,
  season: number
): Promise<PlayerForecast | null> {
  if (!fideId || season !== forecast.season) return null

  // Only women have Ladies odds, and a woman who makes both teams takes the Ladies place.
  const order: ForecastCategory[] = ['ladies', 'open']
  const categories = order.flatMap(category => {
    const entry = forecast.categories[category].players[fideId]
    return entry ? [{ category, entry, cutoff: forecast.categories[category].cutoff }] : []
  })
  if (categories.length === 0 || !(await matchesPublishedResults(season))) return null

  return {
    season: forecast.season,
    afterEvent: forecast.after.name,
    sims: forecast.sims,
    categories,
  }
}
